apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do echo "$(date) - Writing to hostPath volume" >> /data/hostpath-log.txt; sleep 5; done']
    volumeMounts:
    - name: hostpath-volume
      mountPath: /data
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /tmp/hostdata
      type: DirectoryOrCreate
